### PR TITLE
Nuke

### PR DESCRIPTION
**Pull request by rgbkrk**
This only leaves a README stating exactly:

# developer.rackspace.com

developer.rackspace.com is now split across several repositories, backed by the [deconst engine](https://github.com/deconst).

There are two sections of the site, `/docs` and everything else:

* `/docs` - [github.com/rackerlabs/docs-quickstart](https://github.com/rackerlabs/docs-quickstart)
* `/`, `/blog`, `/sdks`, etc. - [github.com/rackerlabs/docs-developer-blog](https://github.com/rackerlabs/docs-developer-blog)

Contribute in those repositories to reflect changes, submit blog posts, raise issues, demand ransom, eat cake, and encourage a vibrant community.

If you want to see behind the covers to know the layout, check out the [control repository](https://github.com/rackerlabs/nexus-control).

### CODE REVIEW

**Comment by smashwilson** [comment]
I'm worried about what this will do to the Jenkins builds, and I'm not quite ready to trash the running system just yet - I'm leaving it up for a week or so, so that we can cut back to it quickly if everything crashes horribly on the new system.

We *could* just kill the Jenkins servers and leave the rest running, though. :thought_balloon:

**Comment by rgbkrk** [comment]
image

**Comment by rgbkrk** [comment]
image

**Comment by ianthewhite** [comment]
I agree with the joker. (I can't believe I'm saying this)

**Comment by smashwilson** [comment]
:laughing: 

Alright. I'll :skull: when I hit a breaking point here. Right now I live in a universe of boxes and packing tape.

**Comment by rgbkrk** [comment]
Yeah, it'll be fine to have it as a backup for now and nuke after you get settled.

**Pull request closed without merging**
