### PR TITLE
Added authentication variable info to each service

### PR DESCRIPTION
**Pull request by mdarby**
From Trello card:
https://trello.com/c/A8HSRv7W

I've added this blurb to all services so that users may quickly have access to instructions concerning their username/apikey/region

rackspace developer center 2015-05-11 13-10-35

### CODE REVIEW

**Comment by rgbkrk** [comment]
This seems like a good area where we should have a portion of this expand so a reader of multiple pages isn't having to skim through the same bits every time but a new reader can click to show a bit more on the same page.

That being said, this is well done and doesn't add too much to the current text. It also kills a lot of the repeated text everywhere using the includes. :tada:

Do I have to be pedantic and tell you to target dev? I'd rather just :shipit: and move forward.

**Comment by mdarby** [comment]
`dev` branch should be used only for code (html, js, css, etc.) changes and infrastructure automation changes PRs.

PRs against `master` should only be for docs, blog posts or other text content.

:trollface:

**Comment by rgbkrk** [comment]
Well look at you Mr. CONTRIBUTING.md

OMG, your initials are md... MD... Markdown!!!!

**Comment by mdarby** [comment]
:heart: :shipit:

**Comment by rgbkrk** [comment]
Oops, these deleted `.. include::  samples/authentication.rst`, which made each example lose their respective setup instructions for the section.

**Comment by kenperkins** [comment]
see #1136 for the new issue.

**Pull request merged**
