### PR TITLE
Monitoring Hadoop with Rackspace Cloud services — managing partial failure

### PR DESCRIPTION
**Pull request by dajobe**
Including my answers to 
https://github.com/rackerlabs/developer.rackspace.com/blob/master/src/site_source/CONTRIBUTING.md#submitting-your-blog-entries

1. Bio

It is in the article.  Here it is again: 

Dave Beckett is a software engineer with a background in multiple data and web metadata systems (from RDF to CSV) working in the Rackspace Data Platform group. He spends most of his time tending the Hadoop cluster and writing Python to automate that. Dave lives in San Francisco with his wife and in his spare time codes on his free software projects such as Redland RDF http://librdf.org/ More details at http://www.dajobe.org/ and https://github.com/dajobe/

2. Social media contact info:

I am dajobe on Twitter and github

3. I decline to allow redaction, editing or structure changes by technical writer staff

I want to be involved in changes.

4. desired date of publishing

None.  To be coordinated with me, Nick Kolegraff and Kenny Gorman

### CODE REVIEW

**Comment by rdodev** [comment]
paging @catlook and @ycombinator I no longer have commit privileges here.

**Comment by rgbkrk** [comment]
Looking great to me. Thanks for the post!

**Comment by rgbkrk** [comment]
I can publish this now if you like, but Friday evening may not be the best release time for putting out a blog post.

**Comment by dajobe** [comment]
@rgbkrk please don't publish it. we want to coordinate this properly

**Comment by rgbkrk** [comment]
Sounds great, you'll just have to update the date in your title and filenames.

**Comment by kgorman** [comment]
@dajobe want to update the dates as Kyle says and I will merge?

**Comment by dajobe** [comment]
@kgorman what date do you want to publish it?

**Comment by kgorman** [comment]
@dajobe it's up to you, anytime. Let's do it!

**Comment by koooee** [comment]
@dajobe @kgorman lets do it on Monday Feb. 16th

**Pull request merged**
