### PR TITLE
Unify _config.yml into a single template

### PR DESCRIPTION
**Pull request by smashwilson**
Use a single `_config.yml` Jinja template for both the `dev` role and the `jenkins_push.yml` playbook, rather than two separate ones. Gotta keep it DRY :umbrella: 

- [x] Parameterize `templates/_config.yml.j2` further to be able to generate the dev version of the config.
- [x] Provide appropriate variables in `dev_web.yml`.
- [x] Provide appropriate variables in `jenkins_push.yml`.
- [x] *(Optional)* provide a way to generate a sane `_config.yml` for non-Vagrant blog writing.
- [x] Test Vagrant provisioning.
- [x] Test Jenkins page builds.

Fixes #540.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Mr. @smashwilson, how are you feeling about this PR now. Care to rebase?

**Comment by smashwilson** [comment]
> Mr. @smashwilson, how are you feeling about this PR now. Care to rebase?

Hah. Haven't touched it in months. I'd be happy to revisit, although there's the question of whether or not it's worth the time with a redesign in the pipes.

**Comment by rgbkrk** [comment]
Yeah a lot of these issues I'd like to shelve before we get started on the mass explosion into smaller individual repos and a redesign.

**Comment by smashwilson** [comment]
Er, "shelve" meaning "close and disregard", or "shelve" meaning "fix with code"?

This one wasn't *too* big of a deal. At this point the biggest difficulty would be remembering where everything was, because it's been a while since I've looked at this setup. (Also, resisting the temptation to touch a bunch of other things along the way.)

I suppose it depends on how much pain this is causing us in the interim, especially now that `script/preview` is using the Docker image anyway.

**Comment by smashwilson** [comment]
:skull:

**Pull request closed without merging**
