### PR TITLE
Getting started guide for the Rackspace CDN service

### PR DESCRIPTION
**Pull request by ycombinator**
This PR adds the narrative and initial sample files for the Rackspace CDN getting started guide. There will be separate PRs from each SDK author for filling in the sample files with code snippets for their SDK.

### CODE REVIEW

**Comment by rdodev** [comment]
I'll check in more detail in the morning, Shaunak. But at first glance the
phrasing seems to be biased toward "web site". Is that the main use or
intent of new Rackspace CDN?

On Monday, January 19, 2015, Shaunak Kashyap <notifications@github.com>
wrote:

> This PR adds the narrative and initial sample files for the Rackspace CDN
> getting started guide. There will be separate PRs from each SDK author for
> filling in the sample files with code snippets for their SDK.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rackerlabs/developer.rackspace.com/pull/1019
> Commit Summary
>
>    - Narrative for Rackspace CDN getting started guide.
>    - Initial samples for Rackspace CDN getting started guide.
>
> File Changes
>
>    - *A* src/docs/cdn/getting-started/index.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-0>
>    (115)
>    - *A* src/docs/cdn/getting-started/samples/authentication.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-1>
>    (37)
>    - *A* src/docs/cdn/getting-started/samples/create_service.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-2>
>    (50)
>    - *A* src/docs/cdn/getting-started/samples/delete_service.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-3>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/get_flavor.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-4>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/get_service.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-5>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/list_flavors.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-6>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/list_services.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-7>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/purge_all_service_assets.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-8>
>    (29)
>    - *A*
>    src/docs/cdn/getting-started/samples/purge_specific_service_asset.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-9>
>    (29)
>    - *A* src/docs/cdn/getting-started/samples/update_service.rst
>    <https://github.com/rackerlabs/developer.rackspace.com/pull/1019/files#diff-10>
>    (49)
>
> Patch Links:
>
>    - https://github.com/rackerlabs/developer.rackspace.com/pull/1019.patch
>    - https://github.com/rackerlabs/developer.rackspace.com/pull/1019.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackerlabs/developer.rackspace.com/pull/1019>.
>


-- 
Sent from Gmail Mobile

**Comment by ycombinator** [comment]
Yes, the Rackspace CDN service will allow users to cache their static web site (hosted on some origin server) on a CDN's edge nodes.

**Comment by DonSchenck** [comment]
Two EXTREMELY minor grammar things, otherwise looks good to me.

**Comment by rdodev** [comment]
In terms of content I've got couple of suggestions:
 - Consider adding a blurb about encryption, security considerations and support
 - Maybe a paragraph or two as to how RackspaceCDN differs from setting a CloudFiles container as CDN.

**Comment by DonSchenck** [comment]
The line "A CDN is designed to improve performance of publicly distributed assets" should read "A CDN is designed to improve performance of publicly-distributed assets".

In the first line, I believe "CDN enable" should be "CDN-enable".

**Comment by ChristieQ** [comment]
Hi All,

"Publicly distributed assets" is correct (no hyphens on adverbs). Also, in the existing context, "CDN enable" is correct.

Thanks!
Christie

**Comment by ycombinator** [comment]
@rdodev: This is ready for review again.

**Comment by ycombinator** [comment]
Okay, @rdodev, _now_ this is ready for review again.

**Comment by rdodev** [comment]
:boom:

**Pull request merged**
