### PR TITLE
Data.rackspace.com v0

### PR DESCRIPTION
**Pull request by kgorman**

### CODE REVIEW

**Comment by kenperkins** [comment]
If this is ready to go, we need a CR, @ycombinator or @rdodev are you available to assist here?

**Comment by rdodev** [comment]
@kgorman would you mind re-targeting this PR against `dev` branch so we can see it deploy on staging before pushing to production?

**Comment by kgorman** [comment]
Sure, NP, let me do that.

**Comment by rdodev** [comment]
Looks good on staging. Merging to `master`

**Pull request merged**
