### PR TITLE
rpcv9 ansible blog post update2

### PR DESCRIPTION
**Pull request by wbentley15**
Bios:
Walter Bentley – Rackspace Private Cloud Solutions Architect – Walter is a new Racker with a diverse background in Production Systems Administration and Solutions Architecture. He brings over 15 years of experience across numerous industries such as Online Marketing, Financial, Insurance, Aviation, Food Industry and Education. In the past, always being the requestor, consumer and advisor to companies to use technologies such as OpenStack, now promoter of OpenStack technology and Cloud educator.

Twitter: @djstayflypro
LinkedIn: http://goo.gl/r2p21i
Github: wbentley15

Accept to allow redaction, editing or structure changes by technical writer staff desired date of publishing
Publish date: 11-17-2014

### CODE REVIEW

**Comment by wbentley15** [comment]
@rdodev ok...hope this is what you wanted

**Comment by rdodev** [comment]
:+1: Thanks. Merging.

**Comment by rdodev** [comment]
It's not so much what *I* wanted. It's more than git doesn't allow you to merge into an already-closed PR :)

**Comment by wbentley15** [comment]
@rdodev understood...totally understand and man that was quick merging my friend

**Pull request merged**
