### PR TITLE
Deploying JupyterHub for Education

### PR DESCRIPTION
**Pull request by jhamrick**
1. Bio: Jess Hamrick is a PhD student in the Psychology Department at UC Berkeley, having previously earned a BS and MEng in Computer Science and Engineering from MIT. Jess is an avid Pythonista, and when she's not doing research on how the mind works, she enjoys contributing to open source projects like IPython and JupyterHub.
2. Twitter: @jhamrick
3. I accept to allow redaction, editing or structure changes by technical writer staff
4. Desired date of publishing: Tuesday, March 24th 2015

ping @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
Yay! Thanks Jess! Really looking forward to this.

Ping @catlook for extra review (@minrk and I did some editing earlier).

**Comment by DonSchenck** [comment]
+1 Looks great.

**Comment by rgbkrk** [comment]
Time to :shipit:

**Comment by jhamrick** [comment]
Woohoo, thanks! :tada:

**Comment by rgbkrk** [comment]
Thank YOU!

**Pull request merged**
