### PR TITLE
Raise the profile of the SDK feeds to encourage upgrading

### PR DESCRIPTION
**Pull request by everett-toews**
This is WIP. Only did Go so far so we can just review that and then I'd do the same for the rest of the SDKs. Note that I'd be normalizing the "Links" section of the respective SDKs as part of this change.

### CODE REVIEW

**Comment by rdodev** [comment]
LGTM. @ChristieQ has been contacted for input.

**Comment by rdodev** [comment]
@ChristieQ when you get a chance, can you check this out?

**Comment by ChristieQ** [comment]
Looks good to me! Thanks :)

**Comment by rdodev** [comment]
@everett-toews do you want me to merge this first or wait until you're done with the rest of the SDKs?

**Comment by everett-toews** [comment]
Wait please

**Comment by everett-toews** [comment]
@rdodev Okay. The rest of the SDKs are done.

**Comment by rdodev** [comment]
Cool beans! Let me give it a last check and merge.

**Pull request merged**
