### PR TITLE
Be more explicit about the clear-text secrets

### PR DESCRIPTION
**Pull request by kenperkins**
@smashwilson feel like we could be a bit more obvious here, in case someone ever forgets to remove the artifact later.

### CODE REVIEW

**Comment by smashwilson** [comment]
:+1: Works for me.

**Comment by smashwilson** [comment]
You'll also need to update the places that import it as a var file. This:

```yaml
  vars_files:
  - vars.yml
  - [ 'secrets.yml', 'secrets.vault.yml' ]
```

will need to be:

```yaml
  vars_files:
  - vars.yml
  - [ 'secrets-clear-text.yml', 'secrets.vault.yml' ]
```

Ansible prefers the clear-text, ignored version because I also use this to deploy to different accounts while I'm making infrastructure changes.

**Comment by kenperkins** [comment]
So Updated

**Comment by smashwilson** [comment]
Yep, there we go.

**Pull request merged**
