### PR TITLE
Add info about 2x/quarter support interactions

### PR DESCRIPTION
**Pull request by ChristieQ**

### CODE REVIEW

**Comment by rdodev** [comment]
@ChristieQ can we merge this change?

**Comment by ChristieQ** [comment]
Hi @rdodev - Still need answers from @everett-toews on my last message above.

**Comment by rgbkrk** [comment]
Any update on this @everett-toews? We could merge as is and make further refinements in a new PR too.

**Comment by ChristieQ** [comment]
@rgbkrk: Spoke with @everett-toews, and he's deferring to @jnoller for answers to my ticketing questions. I believe that we can commit as is, and update later, if needed.

**Comment by everett-toews** [comment]
Considering we have https://developer.rackspace.com/support/ now, I'd prefer it if we just linked to that from here for consistency sake.

**Comment by rgbkrk** [comment]
Okee doke.

**Comment by ChristieQ** [comment]
I think Everett meant to leave that comment on issue #1039

**Comment by everett-toews** [comment]
Superseded by https://github.com/rackerlabs/developer.rackspace.com/pull/1045

**Pull request closed without merging**
