### PR TITLE
Adding pyrax samples for Rackspace CDN

### PR DESCRIPTION
**Pull request by ycombinator**
Please **DO NOT MERGE** until https://github.com/rackspace/pyrax/pull/552 is merged and a new version of pyrax featuring support for Rackspace CDN is released.

### CODE REVIEW

**Comment by rgbkrk** [comment]
#548 was closed. What's the state on this now?

**Comment by ycombinator** [comment]
> #548 was closed. What's the state on this now?

https://github.com/rackspace/pyrax/pull/548 was superseded by https://github.com/rackspace/pyrax/pull/552. I have updated the description of this PR to point to 552.

**Comment by mdarby** [comment]
@briancurtin Is this cool to merge/release?

**Comment by briancurtin** [comment]
yeah sure/yes sir

**Comment by mdarby** [comment]
Thank ya buddy!

**Pull request merged**
