### PR TITLE
Corrected 2013 -> 2014

### PR DESCRIPTION
**Pull request by gecampbell**
incorrect date in article.

### CODE REVIEW

**Comment by rdodev** [comment]
@smashwilson would this commit with subtree screw things up?

**Comment by smashwilson** [comment]
@rdodev Oh. Yes, it likely would. Aren't submodules irritating?

#1034 also has a redundant fix (but that's fine, I'll just have rebase).

**Comment by rdodev** [comment]
@gecampbell do you mind if I submit the fix to the date? If we merge this PR it will break things due to the subtree commit.

**Comment by rgbkrk** [comment]
Since the submodule bit here shouldn't be included, I'll close this PR since I merged #1034. I'll address the year manually now.

**Pull request closed without merging**
